//! Embedded template table; `registry` is generated by `build.rs` from
//! the fetched exemplar `templates/guest/manifest.yaml`.

/// One static scaffold file: contents are written verbatim to `target`
/// (relative to the project root).
pub(super) struct TemplateEntry {
    pub target: &'static str,
    pub contents: &'static str,
}

pub(super) mod registry {
    include!(concat!(env!("OUT_DIR"), "/template_registry.rs"));
}
