//! Embedded template table; `registry` is generated by `build.rs` from
//! `templates/manifest.yaml`.

pub(super) mod registry;

/// One static scaffold file: contents are written verbatim to `target`
/// (relative to the project root).
pub(super) struct TemplateEntry {
    pub target: &'static str,
    pub contents: &'static str,
}
