// @generated by build.rs — do not edit

#[rustfmt::skip]
pub mod core {
    use crate::scaffold::templates::TemplateEntry;

    pub const ENTRIES: &[TemplateEntry] = &[
        TemplateEntry {
            target: "Makefile",
            contents: include_str!("../../../templates/core/Makefile"),
        },
        TemplateEntry {
            target: "Makefile.toml",
            contents: include_str!("../../../templates/core/Makefile.toml"),
        },
        TemplateEntry {
            target: "deny.toml",
            contents: include_str!("../../../templates/core/deny.toml"),
        },
        TemplateEntry {
            target: "rust-toolchain.toml",
            contents: include_str!("../../../templates/core/rust-toolchain.toml"),
        },
        TemplateEntry {
            target: "rustfmt.toml",
            contents: include_str!("../../../templates/core/rustfmt.toml"),
        },
        TemplateEntry {
            target: "clippy.toml",
            contents: include_str!("../../../templates/core/clippy.toml"),
        },
        TemplateEntry {
            target: "taplo.toml",
            contents: include_str!("../../../templates/core/taplo.toml"),
        },
        TemplateEntry {
            target: ".gitignore",
            contents: include_str!("../../../templates/core/gitignore"),
        },
        TemplateEntry {
            target: ".cargo/config.toml",
            contents: include_str!("../../../templates/core/cargo-config.toml"),
        },
        TemplateEntry {
            target: ".vscode/settings.json",
            contents: include_str!("../../../templates/core/vscode-settings.json"),
        },
        TemplateEntry {
            target: "supply-chain/README.md",
            contents: include_str!("../../../templates/core/supply-chain-README.md"),
        },
        TemplateEntry {
            target: "supply-chain/config.toml",
            contents: include_str!("../../../templates/core/supply-chain-config.toml"),
        },
        TemplateEntry {
            target: "supply-chain/audits.toml",
            contents: include_str!("../../../templates/core/supply-chain-audits.toml"),
        },
        TemplateEntry {
            target: ".github/workflows/audit.yaml",
            contents: include_str!("../../../templates/core/workflow-audit.yaml"),
        },
        TemplateEntry {
            target: ".github/workflows/ci.yaml",
            contents: include_str!("../../../templates/core/workflow-ci.yaml"),
        },
        TemplateEntry {
            target: ".github/workflows/patch.yaml",
            contents: include_str!("../../../templates/core/workflow-patch.yaml"),
        },
        TemplateEntry {
            target: ".github/workflows/release.yaml",
            contents: include_str!("../../../templates/core/workflow-release.yaml"),
        },
        TemplateEntry {
            target: ".github/workflows/publish.yaml",
            contents: include_str!("../../../templates/core/workflow-publish.yaml"),
        },
    ];
}
