# Install: `cargo install cargo-make`
# Help: https://sagiegurari.github.io/cargo-make/

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = true
skip_core_tasks = true
skip_crate_env_info = true
skip_git_env_info = true
skip_rust_env_info = true

# -------------------------------------
# CI Checks
# -------------------------------------
[tasks.check]
dependencies = ["fmt", "lint", "test", "test-docs", "doc"]

[tasks.ci]
dependencies = ["check", "vet", "deny"]

# -------------------------------------
# Actions
# -------------------------------------

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.deny]
command = "cargo"
args = ["deny", "check"]
install_crate = "cargo-deny"

[tasks.deps]
command = "rustup"
args = ["run", "nightly", "cargo", "udeps", "--workspace", "--all-targets"]
install_crate = "cargo-udeps"

[tasks.fmt]
script = "cargo +nightly fmt --all"

[tasks.lint]
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]
install_crate = { rustup_component_name = "clippy" }

[tasks.outdated]
command = "cargo"
args = ["outdated", "--depth", "1"]
install_crate = "cargo-outdated"

[tasks.test]
command = "cargo"
args = ["nextest", "run", "--workspace", "--all-features", "--no-tests=pass"]
env = { RUSTFLAGS = "-Dwarnings" }

[tasks.test-docs]
command = "cargo"
args = ["test", "--doc", "--workspace", "--all-features"]

[tasks.doc]
command = "cargo"
args = ["doc", "--no-deps", "--workspace", "--all-features", "--locked"]
env = { RUSTDOCFLAGS = "-Dwarnings" }

[tasks.vet]
script = '''
cargo vet regenerate imports
cargo vet regenerate exemptions
cargo vet regenerate unpublished
cargo vet --locked
'''
install_crate = "cargo-vet"
