//! Embeds every markdown document under the adapter's `prose/` tree as
//! the sorted `DOCS` table `src/registry.rs` includes (symlinks resolve
//! at build time), and fetches the Omnia guest-template contract from
//! [`augentic/omnia-exemplar`](https://github.com/augentic/omnia-exemplar)
//! into `OUT_DIR` so the scaffold registry can `include_str!` it.
//!
//! The exemplar owns `templates/guest/` — this crate never commits a
//! second copy. Resolution order:
//!
//! 1. `OMNIA_EXEMPLAR` — path to a local exemplar checkout
//! 2. Sibling checkout at `../../../omnia-exemplar` (peer of this repo)
//! 3. Shallow clone of `main` into the cargo target dir (refreshed each build)
//!
//! Do not hand-edit template bodies here; change them upstream.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

use jsonschema::Validator;
use serde::Deserialize;

const SCHEMA_VERSION: i64 = 2;
const ASSEMBLY_ORDER: &[&str] = &["core"];
const EXEMPLAR_REPO: &str = "https://github.com/augentic/omnia-exemplar";

fn main() {
    prose::emit("prose");
    if let Err(err) = generate_template_registry() {
        panic!("omnia template fetch/codegen failed: {err}");
    }
}

fn generate_template_registry() -> Result<(), String> {
    let out_dir = PathBuf::from(env::var("OUT_DIR").map_err(|err| err.to_string())?);
    let templates_root = resolve_templates_guest(&out_dir)?;
    let staged = stage_templates(&templates_root, &out_dir)?;

    let manifest_path = staged.join("manifest.yaml");
    let schema_path = staged.join("manifest.schema.json");
    let registry_out = out_dir.join("template_registry.rs");

    println!("cargo:rerun-if-env-changed=OMNIA_EXEMPLAR");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed={}", schema_path.display());

    let manifest_text = fs::read_to_string(&manifest_path)
        .map_err(|err| format!("read {}: {err}", manifest_path.display()))?;
    let schema_text = fs::read_to_string(&schema_path)
        .map_err(|err| format!("read {}: {err}", schema_path.display()))?;

    let manifest_value: serde_json::Value = serde_saphyr::from_str(&manifest_text)
        .map_err(|err| format!("parse {}: {err}", manifest_path.display()))?;
    validate_schema(&schema_text, &manifest_value)?;

    let manifest: Manifest = serde_saphyr::from_str(&manifest_text)
        .map_err(|err| format!("deserialize {}: {err}", manifest_path.display()))?;
    if manifest.schema_version != SCHEMA_VERSION {
        return Err(format!(
            "unsupported schema-version {} (expected {SCHEMA_VERSION})",
            manifest.schema_version
        ));
    }

    for assembly in ASSEMBLY_ORDER {
        let spec = manifest
            .assemblies
            .get(*assembly)
            .ok_or_else(|| format!("assemblies.{assembly} is missing"))?;
        detect_orphans(assembly, &staged.join(assembly), spec)?;
    }

    let mut out = String::from("// @generated by build.rs — do not edit\n\n");
    for assembly in ASSEMBLY_ORDER {
        let spec = manifest
            .assemblies
            .get(*assembly)
            .ok_or_else(|| format!("assemblies.{assembly} is missing"))?;
        emit_assembly(&mut out, assembly, spec)?;
    }

    while out.ends_with("\n\n") {
        out.pop();
    }

    fs::write(&registry_out, out)
        .map_err(|err| format!("write {}: {err}", registry_out.display()))?;

    // Tests read the fetched manifest without re-resolving the exemplar.
    println!("cargo:rustc-env=OMNIA_TEMPLATES_DIR={}", staged.display());
    Ok(())
}

/// Locate `templates/guest/` — env override, sibling checkout, or clone.
fn resolve_templates_guest(out_dir: &Path) -> Result<PathBuf, String> {
    if let Ok(path) = env::var("OMNIA_EXEMPLAR") {
        let root = PathBuf::from(path);
        return validate_exemplar(&root).map(|()| root.join("templates/guest"));
    }

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(|err| err.to_string())?);
    // `targets/omnia` → repo root → peer `omnia-exemplar`.
    let sibling = manifest_dir.join("../../..").join("omnia-exemplar");
    if sibling.join("exemplar.yaml").is_file() {
        validate_exemplar(&sibling)?;
        return Ok(sibling.join("templates/guest"));
    }

    let cache = target_cache_dir(out_dir)?.join("omnia-exemplar");
    refresh_clone(&cache)?;
    validate_exemplar(&cache)?;
    Ok(cache.join("templates/guest"))
}

fn target_cache_dir(out_dir: &Path) -> Result<PathBuf, String> {
    // OUT_DIR is `…/target/<profile>/build/<crate>/out`. Walk to `target/`.
    out_dir
        .ancestors()
        .find(|path| path.file_name().is_some_and(|name| name == "target"))
        .map(Path::to_path_buf)
        .ok_or_else(|| format!("cannot locate target/ above OUT_DIR {}", out_dir.display()))
}

fn refresh_clone(cache: &Path) -> Result<(), String> {
    if cache.join(".git").is_dir() {
        run_git(cache, &["fetch", "--depth", "1", "origin", "main"])?;
        run_git(cache, &["reset", "--hard", "origin/main"])?;
        return Ok(());
    }
    if cache.exists() {
        fs::remove_dir_all(cache)
            .map_err(|err| format!("remove stale {}: {err}", cache.display()))?;
    }
    if let Some(parent) = cache.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    let status = Command::new("git")
        .args(["clone", "--depth", "1", "--branch", "main", EXEMPLAR_REPO])
        .arg(cache)
        .status()
        .map_err(|err| format!("git clone {EXEMPLAR_REPO}: {err}"))?;
    if !status.success() {
        return Err(format!("git clone {EXEMPLAR_REPO} failed with {status}"));
    }
    Ok(())
}

fn run_git(cwd: &Path, args: &[&str]) -> Result<(), String> {
    let status = Command::new("git")
        .args(args)
        .current_dir(cwd)
        .status()
        .map_err(|err| format!("git {args:?} in {}: {err}", cwd.display()))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("git {args:?} in {} failed with {status}", cwd.display()))
    }
}

fn validate_exemplar(root: &Path) -> Result<(), String> {
    let exemplar_yaml = root.join("exemplar.yaml");
    if !exemplar_yaml.is_file() {
        return Err(format!(
            "{} has no exemplar.yaml — set OMNIA_EXEMPLAR to a valid omnia-exemplar checkout",
            root.display()
        ));
    }
    let text = fs::read_to_string(&exemplar_yaml)
        .map_err(|err| format!("read {}: {err}", exemplar_yaml.display()))?;
    if !text.lines().any(|line| line.starts_with("  rev:")) {
        return Err(format!("{} declares no omnia rev", exemplar_yaml.display()));
    }
    let manifest = root.join("templates/guest/manifest.yaml");
    if !manifest.is_file() {
        return Err(format!("{} missing — not an exemplar checkout", manifest.display()));
    }
    Ok(())
}

/// Copy `templates/guest` into `OUT_DIR/omnia-templates` so `include_str!`
/// paths stay stable for the compiled crate even when the source is a
/// live checkout that may move.
fn stage_templates(guest: &Path, out_dir: &Path) -> Result<PathBuf, String> {
    let staged = out_dir.join("omnia-templates");
    if staged.exists() {
        fs::remove_dir_all(&staged)
            .map_err(|err| format!("clear {}: {err}", staged.display()))?;
    }
    copy_dir(guest, &staged)?;
    Ok(staged)
}

fn copy_dir(src: &Path, dst: &Path) -> Result<(), String> {
    fs::create_dir_all(dst).map_err(|err| format!("create {}: {err}", dst.display()))?;
    for entry in fs::read_dir(src).map_err(|err| format!("read {}: {err}", src.display()))? {
        let entry = entry.map_err(|err| format!("read dir entry in {}: {err}", src.display()))?;
        let ty = entry.file_type().map_err(|err| format!("file type: {err}"))?;
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir(&entry.path(), &to)?;
        } else if ty.is_file() {
            fs::copy(entry.path(), &to).map_err(|err| {
                format!("copy {} → {}: {err}", entry.path().display(), to.display())
            })?;
        }
    }
    Ok(())
}

fn validate_schema(schema_text: &str, value: &serde_json::Value) -> Result<(), String> {
    let schema: serde_json::Value =
        serde_json::from_str(schema_text).map_err(|err| format!("parse schema JSON: {err}"))?;
    let validator = Validator::new(&schema).map_err(|err| format!("compile schema: {err}"))?;
    let mut details = String::new();
    for err in validator.iter_errors(value) {
        let _ = writeln!(details, "- {err}");
    }
    if details.is_empty() {
        Ok(())
    } else {
        Err(format!("manifest.yaml failed schema validation:\n{details}"))
    }
}

fn detect_orphans(assembly: &str, assembly_dir: &Path, spec: &AssemblySpec) -> Result<(), String> {
    println!("cargo:rerun-if-changed={}", assembly_dir.display());

    let listed: BTreeSet<String> = spec.files.iter().map(|entry| entry.source.clone()).collect();

    for entry in fs::read_dir(assembly_dir)
        .map_err(|err| format!("read {}: {err}", assembly_dir.display()))?
    {
        let entry =
            entry.map_err(|err| format!("read dir entry in {}: {err}", assembly_dir.display()))?;
        let file_name = entry.file_name();
        let name = file_name.to_string_lossy();
        if !entry.file_type().map_err(|err| format!("file type for {name}: {err}"))?.is_file() {
            continue;
        }
        if !listed.contains(name.as_ref()) {
            return Err(format!(
                "orphan template file {}/{} is not listed in manifest.yaml assemblies.{assembly}.files",
                assembly_dir.display(),
                name
            ));
        }
        println!("cargo:rerun-if-changed={}", entry.path().display());
    }

    for source in &listed {
        let path = assembly_dir.join(source);
        if !path.is_file() {
            return Err(format!(
                "manifest lists missing template source assemblies.{assembly}.files source={source:?} ({})",
                path.display()
            ));
        }
        println!("cargo:rerun-if-changed={}", path.display());
    }
    Ok(())
}

fn emit_assembly(out: &mut String, assembly: &str, spec: &AssemblySpec) -> Result<(), String> {
    out.push_str("#[rustfmt::skip]\n");
    let _ = writeln!(out, "pub mod {assembly} {{");
    out.push_str("    use crate::scaffold::templates::TemplateEntry;\n\n");
    out.push_str("    pub const ENTRIES: &[TemplateEntry] = &[\n");

    for entry in &spec.files {
        out.push_str("        TemplateEntry {\n");
        let _ = writeln!(out, "            target: {:?},", entry.target);
        // Absolute via OUT_DIR so the path is independent of where this
        // generated file is `include!`d from.
        let _ = writeln!(
            out,
            "            contents: include_str!(concat!(env!(\"OUT_DIR\"), \"/omnia-templates/{assembly}/{}\")),",
            entry.source
        );
        out.push_str("        },\n");
    }

    out.push_str("    ];\n");
    out.push_str("}\n\n");
    Ok(())
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct Manifest {
    schema_version: i64,
    #[expect(dead_code, reason = "producer-side token contract; deserialized for strictness")]
    tokens: HashMap<String, String>,
    assemblies: HashMap<String, AssemblySpec>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct AssemblySpec {
    #[expect(dead_code, reason = "schema-locked to content-only; deserialized for strictness")]
    path_mode: String,
    files: Vec<FileEntry>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct FileEntry {
    source: String,
    target: String,
    #[expect(dead_code, reason = "upstream proof mode; deserialized for strictness")]
    proof: String,
}
