[package]
name = "omnia"
description = "Omnia target-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
emery-adapter.workspace = true
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
emery-prose.workspace = true
jsonschema.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true

[dev-dependencies]
jsonschema.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true
tempfile.workspace = true
omnia-testkit.workspace = true
tokio.workspace = true
