//! What the SDK's lookups read of TypeScript and JavaScript.
//!
//! One [`Dialect`], data rather than code, passed to each lookup that reads
//! one.

use emery_sdk::survey::route::Spelling;
use emery_sdk::survey::{ClassSyntax, Dialect};

pub(super) static DIALECT: Dialect = Dialect {
    self_name: "this",
    generic_stems: &["index", "main"],
    structural: &[
        "use",
        "register",
        "mount",
        "plugin",
        "decorate",
        "addHook",
        "hook",
        "listen",
        "connect",
        "disconnect",
        "close",
        "end",
        "then",
        "catch",
        "finally",
        "start",
        "stop",
        "init",
        "initialize",
        "forEach",
        "map",
        "filter",
        "reduce",
        "find",
        "findIndex",
        "some",
        "every",
        "sort",
        "flatMap",
        "Promise",
        "setTimeout",
        "setInterval",
        "setImmediate",
        "nextTick",
        "queueMicrotask",
        "describe",
        "it",
        "test",
        "beforeEach",
        "afterEach",
        "beforeAll",
        "afterAll",
    ],
    listeners: &["on", "once", "addListener", "addEventListener", "prependListener"],
    lifecycle_events: &[
        "error",
        "close",
        "connect",
        "connecting",
        "disconnect",
        "end",
        "ready",
        "open",
        "listening",
        "exit",
        "warning",
        "drain",
        "finish",
        "timeout",
        "reconnecting",
        "SIGINT",
        "SIGTERM",
        "SIGHUP",
        "unhandledRejection",
        "uncaughtException",
        "beforeExit",
    ],
    mocking: &[],
    lifecycle: &[],
    decorator_noise: &[
        "UseGuards",
        "UseInterceptors",
        "UsePipes",
        "UseFilters",
        "HttpCode",
        "Header",
        "Redirect",
        "Bind",
        "SetMetadata",
        "Roles",
        "Public",
        "Version",
        "Transactional",
        "Injectable",
        "Inject",
        "SerializeOptions",
    ],
    decorator_noise_prefixes: &["Api"],
    decorator_hooks: &[],
    hook_keywords: &[],
    type_imports_reach: true,
    openers: &['[', '{'],
    comment_prefixes: &["//", "*"],
    globals: &["fetch"],
    options: &[],
    manifests: &["package.json"],
    barrels: &["index"],
    constructs: Some("new"),
    env_object: Some("process.env"),
    enum_bases: &[],
    class_syntax: ClassSyntax::BRACED,
    described: "a case's title under its suites'",
    // A parameter is `:id`; a pattern spells a wildcard, a regex group, or a
    // bracketed segment.
    route: Spelling {
        pattern: &['*', '{', '(', '['],
        param_name: |segment| segment.trim_start_matches(':'),
    },
};
