//! Compiles the conformance caller and every `sources/*` adapter to a
//! `wasm32-wasip2` component and generates `gen.rs`: one path constant per
//! component plus the `foreach_source!` completeness macro.
//!
//! Patterned on omnia's `crates/test-utils/build.rs`: a nested cargo build
//! into a dedicated target directory under `OUT_DIR`, then each artifact's
//! dep-info registered as `rerun-if-changed` so a prose or SDK edit rebuilds
//! the component.

// The root `clippy.toml` is the guest deny-list; a build script is host code
// whose one job is spawning the nested cargo build.
#![expect(
    clippy::disallowed_types,
    reason = "a build script must spawn cargo for the wasm32 component build"
)]

use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

const WASM_TARGET: &str = "wasm32-wasip2";
const CALLER: &str = "caller";

fn main() {
    // A wasm32 build of this crate is empty; never nest a build from one.
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("wasm32") {
        write_gen("");
        return;
    }

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let root = manifest_dir.join("../..").canonicalize().expect("workspace root");
    let sources_dir = root.join("sources");
    println!("cargo:rerun-if-changed={}", sources_dir.display());
    println!("cargo:rerun-if-changed={}", root.join("examples/caller").display());
    println!("cargo:rerun-if-changed={}", root.join("Cargo.lock").display());

    let sources = source_names(&sources_dir);
    let target_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("components");
    build_components(&root, &target_dir, &sources);

    // Always `debug`: the nested build uses the dev profile regardless of
    // the outer profile.
    let artifacts = target_dir.join(WASM_TARGET).join("debug");
    let mut generated = String::from("// Generated by examples/conformance/build.rs.\n");
    let mut seen = HashSet::new();

    let caller = artifacts.join(format!("{CALLER}.wasm"));
    emit_const(&mut generated, "CALLER", "the conformance caller component", &caller);
    emit_dep_info(&caller, &mut seen);

    let mut arms = String::new();
    for name in &sources {
        let artifact = artifacts.join(format!("{name}.wasm"));
        let constant = format!("SOURCE_{}", name.to_uppercase().replace('-', "_"));
        emit_const(
            &mut generated,
            &constant,
            &format!("the `{name}` adapter component"),
            &artifact,
        );
        emit_dep_info(&artifact, &mut seen);
        let _ = writeln!(
            arms,
            "        #[expect(unused_imports, reason = \"asserts the test exists\")]\n        use \
             self::{} as _;",
            name.replace('-', "_")
        );
    }
    let _ = write!(
        generated,
        "/// Asserts an identically named test exists at the invocation site for every \
         `sources/*` adapter; an adapter without one fails to compile.\n#[macro_export]\nmacro_rules! \
         foreach_source {{\n    () => {{\n{arms}    }};\n}}\n"
    );
    write_gen(&generated);
}

fn emit_const(generated: &mut String, constant: &str, doc: &str, artifact: &Path) {
    assert!(artifact.exists(), "no artifact at {}", artifact.display());
    let path = artifact.to_str().expect("artifact path is UTF-8");
    let _ = writeln!(generated, "/// Path to {doc}.\npub const {constant}: &str = {path:?};");
}

fn write_gen(contents: &str) {
    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("gen.rs");
    fs::write(&out, contents).unwrap_or_else(|err| panic!("writing {}: {err}", out.display()));
}

// Every entry under `sources/` is an adapter crate directory; anything else
// is a layout error.
fn source_names(sources_dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(sources_dir)
        .unwrap_or_else(|err| panic!("reading {}: {err}", sources_dir.display()))
        .map(|entry| {
            let entry = entry.expect("directory entry");
            let path = entry.path();
            assert!(
                path.join("Cargo.toml").is_file(),
                "{} is not an adapter crate (sources/ holds adapter crates only)",
                path.display()
            );
            entry.file_name().to_str().expect("UTF-8 crate name").to_owned()
        })
        .collect();
    names.sort();
    assert!(!names.is_empty(), "no adapter crates under {}", sources_dir.display());
    names
}

fn build_components(root: &Path, target_dir: &Path, sources: &[String]) {
    // Reuse Cargo from the parent build to stay on its toolchain.
    let cargo = env::var_os("CARGO").expect("CARGO is set");
    let mut child = Command::new(cargo);
    child.current_dir(root).args(["build", "--locked", "--target", WASM_TARGET, "-p", CALLER]);
    for name in sources {
        child.args(["-p", name]);
    }
    let deny_warnings = rustflags_deny_warnings();
    sanitize(&mut child);
    child.env("CARGO_TARGET_DIR", target_dir);
    if deny_warnings {
        child.env("RUSTFLAGS", "-Dwarnings");
    }

    let status = child.status().unwrap_or_else(|err| {
        panic!("failed to spawn the {WASM_TARGET} component build: {err}");
    });
    assert!(
        status.success(),
        "the components could not be built; install the target with `rustup target add \
         {WASM_TARGET}` and retry"
    );
}

// Propagate only warning denial to the nested build; other outer flags are
// native-target concerns that don't apply to the wasm32 guests.
fn rustflags_deny_warnings() -> bool {
    env::var("RUSTFLAGS")
        .is_ok_and(|flags| flags.contains("-Dwarnings") || flags.contains("-D warnings"))
}

// Prevent host flags from leaking into wasm; preserve Cargo settings and the
// inherited toolchain to avoid mixed-compiler E0514 failures. When the outer
// command is `cargo clippy`, the workspace wrapper would run clippy-driver
// over the guests' wasm32 dep tree; the components are a plain rustc build.
fn sanitize(child: &mut Command) {
    for (key, _) in env::vars_os() {
        let Some(key) = key.to_str() else { continue };
        let kept = key == "CARGO_HOME" || key == "CARGO_NET_OFFLINE";
        if key.starts_with("CARGO_") && !kept {
            child.env_remove(key);
        }
    }
    for key in ["RUSTFLAGS", "RUSTDOCFLAGS", "RUSTC", "RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER"] {
        child.env_remove(key);
    }
}

// Cargo's extra dep-info sits next to the uplifted artifact (`{name}.d`).
// It lists the crate's sources plus every local path dependency, so edits
// there rebuild the component.
fn emit_dep_info(artifact: &Path, seen: &mut HashSet<String>) {
    let dep_info = artifact.with_extension("d");
    let contents = fs::read_to_string(&dep_info)
        .unwrap_or_else(|err| panic!("reading {} ({err})", dep_info.display()));
    for line in contents.lines() {
        let Some((_, deps)) = line.split_once(": ") else {
            continue;
        };
        // dep-info escapes spaces in paths as `\ `.
        let mut current = String::new();
        for part in deps.split(' ') {
            if let Some(prefix) = part.strip_suffix('\\') {
                current.push_str(prefix);
                current.push(' ');
            } else if !part.is_empty() {
                current.push_str(part);
                if seen.insert(current.clone()) {
                    println!("cargo:rerun-if-changed={current}");
                }
                current.clear();
            }
        }
    }
}
