//! Build-time codegen for adapter guests' embedded prose registries.
//!
//! An adapter core's `build.rs` calls [`emit_core`] with its prose trees
//! (typically `prompts` and `references`). Trees live under `<adapter>/prose/`
//! on disk; registry keys omit the `prose/` prefix (`prompts/build.md`, not
//! `prose/prompts/build.md`). The walk follows
//! directory symlinks (such as `references/spec-runtime` into
//! `codex/references/runtime/` — symlinks do not survive embedding, so
//! the resolved content is inlined under the symlink-name path) and writes
//! `<out_dir>/registry_docs.rs`: one `Doc` entry per markdown file, keyed
//! by its adapter-relative path, with the body pulled in by `include_str!`
//! against the resolved absolute path. The include site supplies the `Doc`
//! type (`adapter::registry::Doc`). A dangling symlink or
//! unreadable tree fails the build.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// [`emit`] for an adapter core's `build.rs`: resolves the adapter root
/// from `CARGO_MANIFEST_DIR` (the core sits at `<adapter>/core`)
/// and the output from `OUT_DIR`.
///
/// # Panics
///
/// Panics on any failure — the caller is a build script and must not
/// limp on.
pub fn emit_core(trees: &[&str]) {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let adapter_root =
        manifest_dir.parent().expect("core crate sits at <adapter>/core under the adapter root");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    if let Err(err) = emit(adapter_root, trees, &out_dir) {
        panic!("prose registry codegen failed for {}: {err}", adapter_root.display());
    }
}

const PROSE_ROOT: &str = "prose";

/// Walk `trees` under `<adapter_root>/prose/` and write the sorted `DOCS`
/// table to
/// `<out_dir>/registry_docs.rs`, printing the `cargo:rerun-if-changed`
/// directives for every directory and document walked.
///
/// A tree that does not exist under `adapter_root` is skipped — adapters
/// share one canonical tree list (`prompts` + `references`) and not every
/// adapter carries every tree.
///
/// # Errors
///
/// Returns a rendered message when an existing tree cannot be walked
/// (including a dangling symlink), when no markdown documents are found
/// across all trees, or when the generated file cannot be written — the
/// caller (a `build.rs`) should fail the build with it.
pub fn emit(adapter_root: &Path, trees: &[&str], out_dir: &Path) -> Result<(), String> {
    let mut docs: Vec<(String, PathBuf)> = Vec::new();
    for tree in trees {
        let root = adapter_root.join(PROSE_ROOT).join(tree);
        if !root.exists() {
            continue;
        }
        walk(&root, tree, &mut docs)?;
    }
    docs.sort_by(|a, b| a.0.cmp(&b.0));
    if docs.is_empty() {
        return Err(format!("no markdown documents found under {}", trees.join("/ or ")));
    }

    let mut out = String::from(
        "// @generated by prose — do not edit\n\
         \n\
         /// Every embedded reference document, sorted by adapter-relative path.\n\
         pub static DOCS: &[Doc] = &[\n",
    );
    for (rel, resolved) in &docs {
        writeln!(
            out,
            "    Doc {{ path: {rel:?}, body: include_str!({resolved:?}) }},",
            resolved = resolved.display().to_string(),
        )
        .map_err(|err| err.to_string())?;
    }
    out.push_str("];\n");

    fs::write(out_dir.join("registry_docs.rs"), out).map_err(|err| err.to_string())
}

// Collect every `.md` file under `dir` as `(adapter-relative path, resolved
// absolute path)`, descending through directory symlinks. `rel` is the
// symlink-name path (prompts reference `references/spec-runtime/...`), while
// the resolved path feeds `include_str!`.
fn walk(dir: &Path, rel: &str, docs: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = fs::read_dir(dir).map_err(|err| format!("read {}: {err}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("walk {}: {err}", dir.display()))?;
        let path = entry.path();
        let child_rel = format!("{rel}/{}", entry.file_name().to_string_lossy());
        // `metadata` follows symlinks; a dangling link errors here, failing
        // the build as the registry contract requires.
        let metadata = fs::metadata(&path)
            .map_err(|err| format!("resolve {} (dangling symlink?): {err}", path.display()))?;
        if metadata.is_dir() {
            walk(&path, &child_rel, docs)?;
        } else if metadata.is_file() && path.extension().is_some_and(|ext| ext == "md") {
            println!("cargo:rerun-if-changed={}", path.display());
            let resolved = fs::canonicalize(&path)
                .map_err(|err| format!("canonicalize {}: {err}", path.display()))?;
            docs.push((child_rel, resolved));
        }
    }
    Ok(())
}
