//! Build-time codegen for adapter guests' embedded prose registries.
//!
//! [`emit`] walks `prose/` (following directory symlinks) and writes a
//! sorted `DOCS` table to `$OUT_DIR/registry_docs.rs`.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// [`emit_from`] for an adapter guest's `build.rs`: the adapter root is
/// `CARGO_MANIFEST_DIR` and the output is `OUT_DIR`.
///
/// # Panics
///
/// Panics on any failure — the caller is a build script and must not
/// limp on.
pub fn emit() {
    let adapter_root =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    if let Err(err) = emit_from(&adapter_root, &out_dir) {
        panic!("prose registry codegen failed for {}: {err}", adapter_root.display());
    }
}

/// Walk `<adapter_root>/prose/` and write the sorted `DOCS` table to
/// `<out_dir>/registry_docs.rs`, printing `cargo:rerun-if-changed` for
/// every directory and document walked.
///
/// The embed set is discovered from disk, not declared by the caller:
/// every markdown document under `prose/` is embedded, keyed by its
/// `prose/`-relative path.
///
/// # Errors
///
/// Returns a rendered message when the `prose/` tree is missing or holds
/// no markdown documents, when it cannot be walked (including a dangling
/// symlink), or when the generated file cannot be written — the caller
/// (a `build.rs`) should fail the build with it.
pub fn emit_from(adapter_root: &Path, out_dir: &Path) -> Result<(), String> {
    let root = adapter_root.join("prose");
    let mut docs: Vec<(String, PathBuf)> = Vec::new();
    if root.is_dir() {
        walk(&root, "", &mut docs)?;
    }
    docs.sort_by(|a, b| a.0.cmp(&b.0));
    if docs.is_empty() {
        return Err(format!("no markdown documents found under {}", root.display()));
    }

    let mut out = String::from(
        "// @generated by prose — do not edit\n\
         \n\
         /// Every embedded reference document, sorted by adapter-relative path.\n\
         pub static DOCS: &[Doc] = &[\n",
    );
    for (rel, resolved) in &docs {
        writeln!(
            out,
            "    Doc {{ path: {rel:?}, body: include_str!({resolved:?}) }},",
            resolved = resolved.display().to_string(),
        )
        .map_err(|err| err.to_string())?;
    }
    out.push_str("];\n");

    fs::write(out_dir.join("registry_docs.rs"), out).map_err(|err| err.to_string())
}

// Collect every `.md` file under `dir` as `(adapter-relative path,
// resolved absolute path)`, descending through directory symlinks.
fn walk(dir: &Path, rel: &str, docs: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = fs::read_dir(dir).map_err(|err| format!("read {}: {err}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("walk {}: {err}", dir.display()))?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let child_rel = if rel.is_empty() { name } else { format!("{rel}/{name}") };
        // `metadata` follows symlinks; a dangling link errors here, failing
        // the build as the registry contract requires.
        let metadata = fs::metadata(&path)
            .map_err(|err| format!("resolve {} (dangling symlink?): {err}", path.display()))?;
        if metadata.is_dir() {
            walk(&path, &child_rel, docs)?;
        } else if metadata.is_file() && path.extension().is_some_and(|ext| ext == "md") {
            println!("cargo:rerun-if-changed={}", path.display());
            let resolved = fs::canonicalize(&path)
                .map_err(|err| format!("canonicalize {}: {err}", path.display()))?;
            docs.push((child_rel, resolved));
        }
    }
    Ok(())
}
