//! Codegen for the embedded prose registry.
//!
//! Walks the adapter's `briefs/` and `references/` trees (following the
//! `references/spec-runtime` symlink into `shared/references/runtime/` —
//! symlinks do not survive embedding, so the walk inlines the resolved
//! content) and emits `$OUT_DIR/registry_docs.rs`: one `Doc` entry per
//! markdown file, keyed by its adapter-relative path, with the body pulled
//! in by `include_str!` against the resolved absolute path. A dangling
//! symlink or unreadable tree fails the build.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    if let Err(err) = run() {
        panic!("contracts prose registry codegen failed: {err}");
    }
}

fn run() -> Result<(), String> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(|err| err.to_string())?);
    let adapter_root = manifest_dir.parent().ok_or("core crate sits under the adapter root")?;

    let mut docs: Vec<(String, PathBuf)> = Vec::new();
    for tree in ["briefs", "references"] {
        let root = adapter_root.join(tree);
        walk(&root, tree, &mut docs)?;
    }
    docs.sort_by(|a, b| a.0.cmp(&b.0));
    if docs.is_empty() {
        return Err("no markdown documents found under briefs/ or references/".to_string());
    }

    let mut out = String::from(
        "// @generated by build.rs — do not edit\n\
         \n\
         /// Every embedded reference document, sorted by adapter-relative path.\n\
         pub static DOCS: &[Doc] = &[\n",
    );
    for (rel, resolved) in &docs {
        writeln!(
            out,
            "    Doc {{ path: {rel:?}, body: include_str!({resolved:?}) }},",
            resolved = resolved.display().to_string(),
        )
        .map_err(|err| err.to_string())?;
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").map_err(|err| err.to_string())?);
    fs::write(out_dir.join("registry_docs.rs"), out).map_err(|err| err.to_string())?;
    Ok(())
}

// Collect every `.md` file under `dir` as `(adapter-relative path, resolved
// absolute path)`, descending through directory symlinks. `rel` is the
// symlink-name path (briefs reference `references/spec-runtime/...`), while
// the resolved path feeds `include_str!`.
fn walk(dir: &Path, rel: &str, docs: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = fs::read_dir(dir).map_err(|err| format!("read {}: {err}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("walk {}: {err}", dir.display()))?;
        let path = entry.path();
        let child_rel = format!("{rel}/{}", entry.file_name().to_string_lossy());
        // `metadata` follows symlinks; a dangling link errors here, failing
        // the build as the registry contract requires.
        let metadata = fs::metadata(&path)
            .map_err(|err| format!("resolve {} (dangling symlink?): {err}", path.display()))?;
        if metadata.is_dir() {
            walk(&path, &child_rel, docs)?;
        } else if metadata.is_file() && path.extension().is_some_and(|ext| ext == "md") {
            println!("cargo:rerun-if-changed={}", path.display());
            let resolved = fs::canonicalize(&path)
                .map_err(|err| format!("canonicalize {}: {err}", path.display()))?;
            docs.push((child_rel, resolved));
        }
    }
    Ok(())
}
