[package]
name = "prose"
description = "Build-time codegen for adapter guests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
