[package]
name = "typescript"
description = "TypeScript source-adapter"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
adapter.workspace = true
core = { path = "core", package = "typescript-core" }
wasip3.workspace = true
